application: teachme-dev
version: v1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "0m"
handlers:

- url: /static
  static_dir: templates/static
  secure: optional

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.html)
  static_files: html/\1
  upload: html/(.*\.html)

- url: /images
  static_dir: apprtc/images

- url: /js
  static_dir: apprtc/js

- url: /css
  static_dir: apprtc/css

- url: /compute/.*
  script: apprtc.apprtc.app
  login: admin

- url: /probe.*
  script: apprtc.probers.app
  secure: always

- url: /session.*
  script: apprtc.apprtc.app
  secure: always

- url: /admin.*
  script: admin.app
  secure: always

- url: /_ah/spi/.*
  script: services.APPLICATION

- url: /live
  script: main.app

- url: /.*
  script: main.app
  secure: always

builtins:
- remote_api: on


inbound_services:
- channel_presence

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

env_variables:
  BYPASS_JOIN_CONFIRMATION: false
